# Full online base_url where is your game
base_url: https://a-312.github.io/ludumdare-basecode/
# Lang for SEO
lang: en

# Your public pseudo/name
author: A-312

# Display name
gamename: Rescue turtles

# Ludum Dare Session Number
ludumdare: 46

# Game version
version: 0.1.3

# Build hash:
#  - 'auto': Generate random uuidv4 at each build (recommanded)
#  - 'cutom': Use custom value
build_version: auto

# Internationalization support (made alternate meta too in head)
alternates:
  en: ./
  # fr: fr/

# SEO title / description / keywords of the page
title: Rescue turtles
description: You are on the beach, you should rescue turtles from gulls
keywords: ludumdare,phaserjs,game,javascript

# Your twitter account set to `false` or `null` if you doesn't have twitter account
twitter:
  account: A312_zds

# Social media card (embed your link :D)
socialcard:
  title: Rescue turtles
  description: You are on the beach, you should rescue turtles from gulls
  image: design/twittercard/banner_ld46_by_c64gamer.png

footer:
  # Display custom text (allow html)
  text: Some turtles born on the beach, save them from gulls ! Have fun ! Arrows or Gamepad (left joystick).
  links:
    "Github Page": https://github.com/A-312/ludumdare-46
    "Ludum Dare Page": https://ldjam.com/events/ludum-dare/46/rescue-turtles-1



# Reserved (DON'T EDIT)
$url: null
